Update gdrive-beta.yml

diff --git a/.github/workflows/gdrive-beta.yml b/.github/workflows/gdrive-beta.yml
--- a/.github/workflows/gdrive-beta.yml
+++ b/.github/workflows/gdrive-beta.yml
@@ -31,6 +31,14 @@ jobs:
           # Unduh file dengan nama asli
           DOWNLOAD_URL="https://www.googleapis.com/drive/v3/files/${FILE_ID}?alt=media"
           curl -L -o $FILE_NAME -H "Authorization: Bearer $GOOGLE_DRIVE_ACCESS_TOKEN" $DOWNLOAD_URL
+          
+          # Verifikasi bahwa file diunduh
+          ls -l $FILE_NAME
+          
+          if [[ ! -f $FILE_NAME ]]; then
+            echo "File image $FILE_NAME not found!"
+            exit 1
+          fi
 
       - name: Extract file and prepare rootfs
         run: |
@@ -70,7 +78,7 @@ jobs:
           # Unmount dan bersihkan
           sudo umount /mnt/rootfs || { echo "Failed to unmount /mnt/rootfs"; exit 1; }
           rmdir /mnt/rootfs || { echo "Failed to remove /mnt/rootfs"; exit 1; }
-          
+
       - name: Upload rootfs.tar.gz to Google Drive
         env:
           GOOGLE_DRIVE_ACCESS_TOKEN: ${{ secrets.GOOGLE_DRIVE_ACCESS_TOKEN }}
@@ -79,9 +87,14 @@ jobs:
           PARENT_FOLDER_ID="1YHEODaFpIJbrsnuu2SoWgqSjrZPkTVzB"
           FILE_NAME="${FILE_NAME%.img}-rootfs.tar.gz"
           
+          if [[ ! -f $FILE_NAME ]]; then
+            echo "File $FILE_NAME not found!"
+            exit 1
+          fi
+          
           # Upload file ke Google Drive
           curl -X POST -L \
             -H "Authorization: Bearer $GOOGLE_DRIVE_ACCESS_TOKEN" \
             -F "metadata={name : '$FILE_NAME', parents : ['$PARENT_FOLDER_ID']};type=application/json;charset=UTF-8" \
             -F "file=@$FILE_NAME;type=application/gzip" \
-            "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
+            "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart" || { echo "Failed to upload file to Google Drive"; exit 1; }
